tower_a = [3,2,1]
tower_b = []
tower_c = []


print(f"A: {tower_a}")
print(f"B: {tower_b}")
print(f"c: {tower_c}")
print("-----------------------------")

tower_b.append(tower_a[-1])
tower_a.pop()
print(f"A: {tower_a}")
print(f"B: {tower_b}")
print(f"c: {tower_c}")
print("-----------------------------")
tower_b.append(tower_a[-1])
tower_a.pop()
print(f"A: {tower_a}")
print(f"B: {tower_b}")
print(f"c: {tower_c}")
print("-----------------------------")
tower_c.append(tower_a[0])
tower_a.pop()
print(f"A: {tower_a}")
print(f"B: {tower_b}")
print(f"c: {tower_c}")
print("-----------------------------")
tower_c.append(tower_b[-1])
tower_b.pop()
print(f"A: {tower_a}")
print(f"B: {tower_b}")
print(f"c: {tower_c}")
print("-----------------------------")
tower_c.append(tower_b[0])
tower_b.pop()
print(f"A: {tower_a}")
print(f"B: {tower_b}")
print(f"c: {tower_c}")
print("-----------------------------")
